CREATE TABLE EMP_TEST (
    NAME VARCHAR2(50)
);

INSERT INTO EMP_TEST (NAME) VALUES ('   Ali   ');
INSERT INTO EMP_TEST (NAME) VALUES ('   Ahmed   ');
INSERT INTO EMP_TEST (NAME) VALUES ('   Sara   ');