CREATE TABLE PRODUCT (
    PRODUCT_NAME VARCHAR2(50)
);

INSERT INTO PRODUCT (PRODUCT_NAME) VALUES ('Laptop');
INSERT INTO PRODUCT (PRODUCT_NAME) VALUES ('Keyboard');
INSERT INTO PRODUCT (PRODUCT_NAME) VALUES ('Mouse');
