INSERT INTO Employees (
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
)
VALUES (
    207, 'Abraam', 'Emad','abraam@gmail.com', '515.123.1234', 
    TO_DATE('2025-12-25', 'YYYY-MM-DD'),
    'AD_PRES', 30000, NULL, NULL, 90
);

COMMIT;
