INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Abraam', 95);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Ahmed', 82);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Sara', 76);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Peter', 65);
INSERT INTO STUDENTS (NAME, MARKS) VALUES ('Ali', 88);
