SELECT 
    NAME,
    MARKS,
    CASE
        WHEN MARKS >= 90 THEN 'A'
        WHEN MARKS BETWEEN 80 AND 89 THEN 'B'
        WHEN MARKS BETWEEN 70 AND 79 THEN 'C'
        ELSE 'F'
    END AS GRADE
FROM STUDENTS;
